'use client'
import { SessionProvider } from 'next-auth/react';
import AuthContext from './context/AuthContext';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <SessionProvider>
        <body className={inter.className}>
          <AuthContext>{children}</AuthContext>
        </body>
      </SessionProvider>
    </html>
  );
}
